# Generated by Django 5.1.6 on 2025-02-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_tracks',
            old_name='artist_name',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='music_tracks',
            old_name='Audio_file',
            new_name='audio_url',
        ),
        migrations.RenameField(
            model_name='music_tracks',
            old_name='track_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='music_tracks',
            name='genre',
        ),
    ]
