# Generated by Django 5.1.6 on 2025-02-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_remove_music_tracks_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_tracks',
            name='userVote',
            field=models.BooleanField(default=False),
        ),
    ]
