# Generated by Django 5.1.6 on 2025-02-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_music_tracks_uservote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_tracks',
            old_name='userVote',
            new_name='like_song',
        ),
    ]
